.TH "lltdscan" "8" "4th September, 2009" "lltdscan" ""

.PP 
.SH "NAME"
lltdscan \- scan for LLTD-enabled hosts on a network interface\&.
.PP 
.SH "SYNOPSIS"
\fBlltdscan\fP [-i \fIiface\fP] [-t \fItimeout\fP] [-u] [-v] [-v] [aa:bb:cc:dd:ee:ff]
.PP 
.SH "DESCRIPTION"
The \fIlltdscan\fP utility sends broadcast \fBLLTD\fP request on specified (or default) interface. And then listens for \fBtimeout\fP milliseconds for responses\&.
.PP 
Add one or two \fB-v\fP options to increase verbosity\&.
.PP 
Add \fB-u\fP option to show machine names in UTF-8\&.
.PP 
Also you can specify exactly one \fBMAC\fP address as last argument - and \fBlltdscan\fP will exit as soon as it receives first reply from specified host\&.
.SH "LLTD PROTOCOL"
\fBLLTD\fP stands for "Link Layer Topology Discovery"\&. 
.PP
Protocol specs are available from Microsoft at http://www\&.microsoft\&.com/whdc/connect/Rally/LLTD-spec\&.mspx
.SH "SEE ALSO"

.PP 
\fBping(8)\fP, \fBarp(8)\fP, \fBarping(8)\fP
.SH "AVAILABILITY"
Check for latest versions at http://github\&.com/zed-0xff/lltdscan
.PP 
And feel free to visit my personal technical blog at http://zed\&.0xff\&.me/ for more fun & useful tools and patches :)
.SH "AUTHOR"

Andrey Zaikin <zed\&.0xff@gmail\&.com>\&.
